vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        magazines:
            uri_prefix: /imgs/upload/magazines
            upload_destination: '%kernel.project_dir%/public/imgs/upload/magazines'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
